import { Inter } from "next/font/google";
import "./globals.css";
import { ToastContainer, Slide } from "react-toastify";
import ReduxProvider from "../redux/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Sunfox Solar Cost and Savings Calculator",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ReduxProvider>
        <body className={inter.className}>{children}</body>
        <ToastContainer
          closeButton={true}
          hideProgressBar={true}
          position="top-right"
          transition={Slide}
          autoClose={3000}
        />
      </ReduxProvider>
    </html>
  );
}
