import { Inter } from "next/font/google";
import "./globals.css";
import { ToastContainer, Slide } from "react-toastify";
// import { Provider } from "react-redux";
// import { store } from "../redux/store";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Sunfox Solar Cost and Savings Calculator",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <Provider store={store}> */}
        <body className={inter.className}>{children}</body>
        <ToastContainer
          closeButton={true}
          hideProgressBar={true}
          position="top-right"
          transition={Slide}
          autoClose={3000}
        />
      {/* </Provider> */}
    </html>
  );
}
